- .github/workflows/gh-pages.yml
> Github Actions support for the Hugo site

- config.toml
> Update github to correct organization

- content/about/index.md
The GitHub repository has a lot of information which is relevant here,
this commit updates the `about/index.md` file to point to the GitHub
repository.
> about: Update to link to GH repository

- config.toml
> Update slack URL

- content/tsc/index.md
> Revert Marvell TSC member

- content/tsc/index.md
Signed-off-by: Paul Pindell <ppindell@gmail.com>
> fixes typo

- content/tsc/index.md
> Add Joe White as TSC Chair

- content/join/index.md
Signed-off-by: Paul Pindell <ppindell@gmail.com>
> Changes from Google form to mailing list method

- content/board/index.md
> Add governing board page

- content/subgroups/index.md
https://github.com/opiproject/opi/commits/main/SUBGROUPS.md
> subgroups: update from latest commits

- content/subgroups/index.md
> subgroups: add leader github handles and calendar

- README.md
> Add developer notes

- content/specs/index.md
> specs: Add approved specs to website

- .github/workflows/gh-pages.yml
This update the version to be the latest.
> CI: Update the version of Ubuntu we run on

- content/subgroups/index.md
> groups: add new link

- content/tsc/index.md
> Update Marvell TSC rep

- content/subgroups/index.md
Signed-off-by: Steven Royer <sroyer@redhat.com>
> Remove PoC group meeting info

- content/specs/index.md
> Add SMBIOS spec after vote

- content/policies/index.md
Add links to all approved OPI TSC policies and procedures
Closes #49
> links: Add links to OPI TSC policies

- config.toml
> add social

- content/subgroups/index.md
Signed-off-by: Paul Pindell <ppindell@gmail.com>
> change from Subgroups to Working Groups
